
        select distinct  ?o1 ?o2 ?o3 ?o4 ?o5 ?o6 where{
            ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.
?n <http://www.openlinksw.com/schemas/virtrdf#qmvftColumnName> ?o2.
?n <http://www.openlinksw.com/schemas/virtrdf#qmvftXmlIndex> ?o3.

            filter (?n = <http://www.openlinksw.com/schemas/virtrdf#DefaultServiceMap-geo>)
        }
    
