
        select distinct  ?o1 ?o2 ?o3 ?o4 where{
            ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.
?n <http://www.openlinksw.com/schemas/virtrdf#qsUserMaps> ?o2.
?n <http://www.openlinksw.com/schemas/virtrdf#qsDefaultMap> ?o3.
?n <http://www.openlinksw.com/schemas/virtrdf#qsMatchingFlags> ?o4.

            filter (?n = <http://www.openlinksw.com/schemas/virtrdf#DefaultServiceStorage>)
        }
    
