
        select distinct ?n where{
            ?n a <http://www.openlinksw.com/schemas/virtrdf#array-of-QuadMap>.
            ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.

            
        }GROUP BY ?n
        HAVING (
            (count(distinct ?o1)=1)
        )
    
