
        select distinct  ?o1 where{
            ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.

            filter (?n = <http://www.openlinksw.com/schemas/virtrdf#DefaultServiceMap-geo-conds>)
        }
    
