
        select distinct ?n where{
            ?n a <http://www.openlinksw.com/schemas/virtrdf#QuadMapFormat>.
            ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.
?n <http://www.openlinksw.com/schemas/virtrdf#qmfName> ?o2.
?n <http://www.openlinksw.com/schemas/virtrdf#qmfSuperFormats> ?o37.
?n <http://www.openlinksw.com/schemas/virtrdf#inheritFrom> ?o38.

            
        }GROUP BY ?n
        HAVING (
            (count(distinct ?o1)=1) && (count(distinct ?o2)=1) && (count(distinct ?o37)=1) && (count(distinct ?o38)=1)
        )
    
