
        select distinct  ?o1 ?o2 ?o3 ?o4 where{
            ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.
?n <http://www.w3.org/2000/01/rdf-schema#label> ?o2.
?n <http://www.w3.org/2000/01/rdf-schema#domain> ?o3.
?n <http://www.w3.org/2000/01/rdf-schema#range> ?o4.

            filter (?n = <http://www.w3.org/2002/07/owl#imports>)
        }
    
