
        select distinct ?n where{
            ?n a <http://www.openlinksw.com/schemas/virtrdf#QuadMapValue>.
            ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.
?n <http://www.openlinksw.com/schemas/virtrdf#qmvTableName> ?o2.
?n <http://www.openlinksw.com/schemas/virtrdf#qmvATables> ?o3.
?n <http://www.openlinksw.com/schemas/virtrdf#qmvColumns> ?o4.
?n <http://www.openlinksw.com/schemas/virtrdf#qmvFormat> ?o5.
?n <http://www.openlinksw.com/schemas/virtrdf#qmvColumnsFormKey> ?o6.

            
        }GROUP BY ?n
        HAVING (
            (count(distinct ?o1)=1) && (count(distinct ?o2)=1) && (count(distinct ?o3)=1) && (count(distinct ?o4)=1) && (count(distinct ?o5)=1) && (count(distinct ?o6)=1)
        )
    
