
        select distinct ?n where{
            ?n a <http://www.w3.org/2002/07/owl#OntologyProperty>.
            ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.
?n <http://www.w3.org/2000/01/rdf-schema#label> ?o2.
?n <http://www.w3.org/2000/01/rdf-schema#domain> ?o3.
?n <http://www.w3.org/2000/01/rdf-schema#range> ?o4.

            
        }GROUP BY ?n
        HAVING (
            (count(distinct ?o1)=2) && (count(distinct ?o2)=1) && (count(distinct ?o3)=1) && (count(distinct ?o4)=1)
        )
    
